Add OCI in 2023 blog post with TOB results
opencontainers/opencontainers.org pull request #125
Opened 2023-01-26 00:32 UTC by caniszczyk

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

2023-01-26 00:33 UTC, samuelkarp requested changes

2023-01-26 00:33 UTC, samuelkarp commented on content/posts/blog/2023-01-26-oci-in-2023.md
> +* Samuel Karp [Amazon]
```suggestion
* Samuel Karp [Google]
```

2023-01-26 00:36 UTC, samuelkarp approved these changes

2023-01-26 00:43 UTC, sudo-bmitch approved these changes

2023-01-27 15:35 UTC, caniszczyk commented
Anything else you want to add @opencontainers/tob on future work?

Any call to actions to get folks involved in future things like auth etc?

2023-01-27 16:28 UTC, jdolitsky approved these changes

2023-01-28 15:18 UTC, merged